# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    desc: Builds the trokhos application
    cmds:
      - go build -o bin/ ./cmd/trokhos/...
